language: generic 
services: 
  - docker

before_install:
  - docker build -t nmaokafor/frontend-docker-app -f Dockerfile.dev .

script:
  - docker run -e CI=true nmaokafor/frontend-docker-app npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "Docker Frontend App"
  env: "docker-environment"
  bucket_name: "elasticbeanstalk-us-east-2-715753550714"
  bucket_path: "Docker Frontend App"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$SECRET_KEY_ID"